[tool.poetry]
name = "oop"
version = "0.1.0"
description = ""
authors = ["Timerkhan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.scripts]
test = "oop.test:test"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
